### Criar entrega
POST http://localhost:8080/entregas
Content-Type: application/json

{
  "formaRecebimento": "Entrega",
  "horarioPreferido": "Manhã",
  "taxaEntrega": 10.0,
  "statusEntrega": "Pendente",
  "pedidoId": 1
}

### Criar retirada
POST http://localhost:8080/entregas
Content-Type: application/json

{
  "formaRecebimento": "Retirada",
  "horarioPreferido": "Tarde",
  "taxaEntrega": 0.0,
  "statusEntrega": "Aguardando retirada",
  "pedidoId": 1
}

### Listar entregas
GET http://localhost:8080/entregas?page=0&size=10

### Buscar entrega
GET http://localhost:8080/entregas/1

### Atualizar entrega
PUT http://localhost:8080/entregas/1
Content-Type: application/json

{
  "formaRecebimento": "Entrega",
  "horarioPreferido": "Noite",
  "taxaEntrega": 10.0,
  "statusEntrega": "Em rota",
  "pedidoId": 1
}

### Deletar entrega
DELETE http://localhost:8080/entregas/1