### Cadastrar usuário
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "MisaelNovo",
  "email": "jonatass@email.com"
}


### Listar usuários
GET http://localhost:8080/usuarios

### Buscar usuário por ID
GET http://localhost:8080/usuarios/1

### Atualizar usuário
PUT http://localhost:8080/usuarios/3
Content-Type: application/json

{
  "nome": "Misael Atualizado",
  "email": "jonatasnovo@email.com"
}


### Deletar usuário
DELETE http://localhost:8080/usuarios/2