### Cadastrar usuário 1
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Gustavo",
  "email": "gustavo@gmail.com",
  "senha": "gustavo123",
  "status": "Ativo"
}

### Cadastrar usuário 2
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Administrador",
  "email": "admin@gmail.com",
  "senha": "12345678",
  "status": "Ativo",
  "tipoUsuario": "ADMINISTRADOR"
}

### Cadastrar usuário 3
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Gustavo",
  "email": "gustavo@email.com"
}

### Cadastrar usuário 4
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "Ana",
  "email": "ana@email.com"
}


### Testar validação
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "nome": "",
  "email": "emailerrado"
}


### Listar usuários paginado
GET http://localhost:8080/usuarios?page=0&size=3


### Listar segunda página
GET http://localhost:8080/usuarios?page=1&size=3

### Buscar usuário por ID
GET http://localhost:8080/usuarios/1


### Atualizar usuário
PUT http://localhost:8080/usuarios/1
Content-Type: application/json

{
  "nome": "Misael Atualizado",
  "email": "jonatasnovo@email.com"
}


### Deletar usuário
DELETE http://localhost:8080/usuarios/1

### Buscar CEP
GET http://localhost:8080/cep/44905000

###

PUT http://localhost:8080/usuarios/1
Content-Type: application/json

{
  "nome": "Administrador",
  "email": "admin@gmail.com",
  "telefone": "(77) 77777-7777",
  "status": "Ativo",
  "tipoUsuario": "ADMINISTRADOR",
  "senhaAtual": "",
  "novaSenha": ""
}